### ISSUE TITLE
Crash on startup - Forge 1.12.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [skeddles/heroicarmory#1]
https://gist.github.com/P3rf3ctXZer0/289fab44589da00f235bb0a8d0618cbc

**Comment by Neglevin** [comment]
I'm having this same issue as well: https://pastebin.com/UxgLsnXx

**Comment by skeddles** [comment]
thanks for your reports and logs. I believe i have fixed the error if you update to 1.1.3
